---
title: "Pomme De Terre Model Review"
author: "Julie Padilla"
date: '2022-06-15'
output: html_document
---

This is an output report for the calibrated Lake Stockton Reservoir Model

```{r libraries, include = FALSE}
library(tidyverse)
library(arrow)
library(glmtools)
library(tidyr)
library(lubridate)
library(kableExtra)
```


```{r setup, include = FALSE}

# ID file paths for inputs
model_folder <- 'nhdhr_106716325_NLDAS_1980_2021'
model_nml <- glmtools::read_nml(nml_file = file.path(model_folder,'glm3.nml'))

nc_file <- file.path(model_folder, get_nml_value(model_nml, "out_dir"),
                     paste0(get_nml_value(model_nml, "out_fn"), '.nc'))
field_file <- file.path(model_folder, 'field_data_nhdhr_106716325.rds')

```

# Observed Data Summary
```{r summarize-data, warning=FALSE}
# subset observed data to modeled values
model_obs <- resample_to_field(nc_file, field_file) %>%
  mutate(year = year(DateTime), month = month(DateTime))

# document unique profiles by month and year
model_obs %>%
  group_by(year, month) %>%
  summarize(n_profile = n_distinct(DateTime)) %>%
  pivot_wider(names_from = year, values_from = n_profile) %>%
  arrange(month) %>%
  kbl() %>%
  kable_styling()
```

# Model-to-Data Comparisons

## Heatmap
```{r heatmap-and-rmse, warning = FALSE}
## Time series comparison
plot_var_compare(nc_file, field_file,
                 precision = 'days', var_name = 'temp') + ## makes a plot!
  ggtitle('Cal Model') +
  theme(plot.title = element_text(hjust = 0.5))
```


```{r rmse-review, warning = FALSE}
# define RMSE function
calc_rmse <- function(mod, obs) {
  # RMSE = √[ Σ(Pi – Oi)2 / n ]
  mse <- mean((obs - mod)^2, na.rm = T)
  sqrt(mse)
}

# calc RMSE by month
rmse_vals <- model_obs %>%
  group_by(year, month) %>%
  summarize(rmse = round(calc_rmse(Modeled_temp, Observed_temp), 2))

# generate tabular summary
rmse_vals %>%
  pivot_wider(names_from = year, values_from = rmse) %>%
  arrange(month) %>%
  kbl() %>%
  kable_styling()

# plot by year
rmse_vals %>%
  arrange(year, month) %>%
  mutate(year = as.factor(year)) %>%
  ggplot(., aes(x = month, y = rmse, group = year, color = year)) +
  geom_point() +
  geom_hline( yintercept = 1.5) +
  # geom_line() +
  facet_wrap(~ year)

# plot by month
rmse_vals %>%
  arrange(year, month) %>%
  ggplot(., aes(x = year, y = rmse)) +
  geom_point() +
  geom_hline( yintercept = 1.5) +
  facet_wrap(~ month)
```


## One-to-one Plot

```{r one-to-one}
# subset data
model_obs <- resample_to_field(nc_file, field_file) %>%
  mutate(month = month(DateTime))

# plot 1-to-1 by month
ggplot(model_obs,
       aes(x = Observed_temp, y = Modeled_temp, color = Depth)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  coord_fixed(ratio = 1) +
  facet_wrap( ~ month) +
  ggtitle('Pomme De Terre Reservoir - 1:1 by Month') +
  theme(plot.title = element_text(hjust = 0.5))
```

## General Observations



## Next Steps

* Calibrate all models


